[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom.variants.design]
capital-j = "serifed"
capital-n = "standard"
capital-q = "crossing"
capital-r = "standing"
capital-w = "straight-vertical-sides"
capital-z = "straight-serifless"
f = "flat-hook"
w = "straight"
long-s = "flat-hook"
lower-lambda = "straight-turn"
lower-mu = "tailed"
cyrl-capital-u = "straight-turn"
cyrl-capital-ya = "standing"
cyrl-ya = "standing"
zero = "slashed"
one = "base"
three = "two-arcs"
four = "closed"
five = "vertical-upper-left-bar"
six = "closed-contour"
eight = "two-circles"
nine = "closed-contour"
asterisk = "hex-low"
underscore = "high"
paren = "flat-arc"
brace = "straight"
ampersand = "upper-open"
at = "short"
dollar = "open"
cent = "open"
percent = "dots"
lig-ltgteq = "slanted"
question = "corner"

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-custom.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-custom.weights.extrabold]
shape = 800
menu = 800
css = 800

[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-custom.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
